// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuLmoVxCOj1wxHhTNo_DU17NOvz9Iy_wk',
    appId: '1:26449658647:web:82d82d36b019abfec6ed52',
    messagingSenderId: '26449658647',
    projectId: 'parts-adda',
    authDomain: 'parts-adda.firebaseapp.com',
    storageBucket: 'parts-adda.firebasestorage.app',
    measurementId: 'G-FZETHMZGT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx_Cur9XgXKpp4yVML0jmBsqA4moacWSA',
    appId: '1:26449658647:android:49156a0df0829c27c6ed52',
    messagingSenderId: '26449658647',
    projectId: 'parts-adda',
    storageBucket: 'parts-adda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByMp1oGeu-l7qhZemfc4orxo-if3cZJ4Q',
    appId: '1:26449658647:ios:3be85a017ace0b26c6ed52',
    messagingSenderId: '26449658647',
    projectId: 'parts-adda',
    storageBucket: 'parts-adda.firebasestorage.app',
    iosBundleId: 'com.example.partsAdda',
  );
}
